### ISSUE TITLE
Plot Improvements in Replay

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/replay#25]
Requested by @skalbfleisch. See dataportal#138 for original post

- [ ] #15 The data should be plotted against the scanned motor by default, not time.
- [ ] #16 The scan list in Replay should be a list rather than a selection via radio buttons
- [ ] #17 A button in Replay to print a scan would be very helpful, also, a button to send it to olog together with some comments.
- [ ] #18 There should be an option to set the upper and lower limit of the plotted axes.
- [x] nsls-ii/dataportal#145 The scaling should be maintained when set manually and a new plot is selected.
- [ ] #19 There should be an option to switch between linear and logarithmic scaling of the plotted axes.
- [ ] #20 There should be an easy way to display multiple scans in one plot.
- [ ] #21 There should be an option to display multiple scalars on multiple y axis of a scan in the same plot. Again, this setting should be maintained, when a new scan is selected.
- [ ] #22 Scaling settings (range, log/linear, etc.)  of the axis should not be overwritten when automatic data update from muxer is activated.
